/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const Head: typeof import('@inertiajs/vue3').Head
  const Link: typeof import('@inertiajs/vue3').Link
  const PROJECT_ROLES: typeof import('../lib/projects').PROJECT_ROLES
  const archiveTypeLabel: typeof import('../lib/archive').archiveTypeLabel
  const categoryBadgeVariant: typeof import('../lib/audit').categoryBadgeVariant
  const cn: typeof import('../lib/utils').cn
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const daysSince: typeof import('../lib/activity').daysSince
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const detectTimezone: typeof import('../lib/timezones').detectTimezone
  const effectScope: typeof import('vue').effectScope
  const formatAuditTimestamp: typeof import('../lib/audit').formatAuditTimestamp
  const formatDateEyebrow: typeof import('../lib/activity').formatDateEyebrow
  const formatDueDate: typeof import('../lib/tasks').formatDueDate
  const formatDuration: typeof import('../lib/meetings').formatDuration
  const formatLastActive: typeof import('../lib/members').formatLastActive
  const formatMeetingDate: typeof import('../lib/meetings').formatMeetingDate
  const formatMeetingTime: typeof import('../lib/meetings').formatMeetingTime
  const formatOccurredAt: typeof import('../lib/archive').formatOccurredAt
  const formatSprintRange: typeof import('../lib/sprints').formatSprintRange
  const getCodeHandler: typeof import('../lib/errors/errorCodeHandlers').getCodeHandler
  const getCsrfToken: typeof import('../lib/csrf').getCsrfToken
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getInitials: typeof import('../composables/useInitials').getInitials
  const getSuggestions: typeof import('../lib/ai-suggestions').getSuggestions
  const greeting: typeof import('../lib/activity').greeting
  const h: typeof import('vue').h
  const handleError: typeof import('../lib/errors/handleError').handleError
  const initializeTheme: typeof import('../composables/useAppearance').initializeTheme
  const inject: typeof import('vue').inject
  const isOverdue: typeof import('../lib/tasks').isOverdue
  const isPastMeeting: typeof import('../lib/meetings').isPastMeeting
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isSupportedTimezone: typeof import('../lib/timezones').isSupportedTimezone
  const isValidMeetingLink: typeof import('../lib/meetings').isValidMeetingLink
  const markRaw: typeof import('vue').markRaw
  const memberPresence: typeof import('../lib/members').memberPresence
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseError: typeof import('../lib/errors/handleError').parseError
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const router: typeof import('@inertiajs/vue3').router
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const sprintStatusLabel: typeof import('../lib/sprints').sprintStatusLabel
  const storeToRefs: typeof import('pinia').storeToRefs
  const timezoneAbbreviation: typeof import('../lib/timezones').timezoneAbbreviation
  const timezoneOffsetLabel: typeof import('../lib/timezones').timezoneOffsetLabel
  const timezoneOptions: typeof import('../lib/timezones').timezoneOptions
  const toDateTimeLocalValue: typeof import('../lib/meetings').toDateTimeLocalValue
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toSpeakableText: typeof import('../composables/useVoiceOutput').toSpeakableText
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateTheme: typeof import('../composables/useAppearance').updateTheme
  const useAiAssistant: typeof import('../composables/useAiAssitant').useAiAssistant
  const useAppearance: typeof import('../composables/useAppearance').useAppearance
  const useAssistantPageContext: typeof import('../composables/useAiAssitant').useAssistantPageContext
  const useAttrs: typeof import('vue').useAttrs
  const useClipboard: typeof import('@vueuse/core').useClipboard
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useCurrentWorkspace: typeof import('../composables/useCurrentWorkspace').useCurrentWorkspace
  const useDark: typeof import('@vueuse/core').useDark
  const useDebounceFn: typeof import('@vueuse/core').useDebounceFn
  const useDockContext: typeof import('../composables/useAiAssitant').useDockContext
  const useFlashToasts: typeof import('../composables/useFlashToasts').useFlashToasts
  const useForm: typeof import('@inertiajs/vue3').useForm
  const useFormErrors: typeof import('../composables/useFormErrors').useFormErrors
  const useId: typeof import('vue').useId
  const useInitials: typeof import('../composables/useInitials').useInitials
  const useLocalStorage: typeof import('@vueuse/core').useLocalStorage
  const useModel: typeof import('vue').useModel
  const useNotificationStore: typeof import('../stores/notification.store').useNotificationStore
  const usePage: typeof import('@inertiajs/vue3').usePage
  const useProjectTaskStream: typeof import('../composables/useProjectTaskStream').useProjectTaskStream
  const useRemember: typeof import('@inertiajs/vue3').useRemember
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToggle: typeof import('@vueuse/core').useToggle
  const useUserTimezone: typeof import('../composables/useUserTimezone').useUserTimezone
  const useVoiceInput: typeof import('../composables/useVoiceInput').useVoiceInput
  const useVoiceOutput: typeof import('../composables/useVoiceOutput').useVoiceOutput
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AssistantState, PendingTool, AssistantMessage } from '../composables/useAiAssitant'
  import('../composables/useAiAssitant')
  // @ts-ignore
  export type { TaskStatusUpdatedPayload } from '../composables/useProjectTaskStream'
  import('../composables/useProjectTaskStream')
  // @ts-ignore
  export type { VoiceInputOptions } from '../composables/useVoiceInput'
  import('../composables/useVoiceInput')
  // @ts-ignore
  export type { ActivityKind, ActivityEntry } from '../lib/activity'
  import('../lib/activity')
  // @ts-ignore
  export type { AIContext } from '../lib/ai-suggestions'
  import('../lib/ai-suggestions')
  // @ts-ignore
  export type { TaskColumnBreakdown, TaskAssigneeBreakdown, ProjectSummary, Analytics, SprintRef, SprintProgress, AnalyticsSprintOption, AnalyticsProjectOption, AnalyticsFilters } from '../lib/analytics'
  import('../lib/analytics')
  // @ts-ignore
  export type { ArchiveRecordType, ArchiveRecord, ArchiveProjectOption, ArchiveAssigneeOption, ArchiveFilters, ArchivePage } from '../lib/archive'
  import('../lib/archive')
  // @ts-ignore
  export type { AuditLogEntry, AuditProjectOption, AuditActorOption, AuditFilters, AuditPage } from '../lib/audit'
  import('../lib/audit')
  // @ts-ignore
  export type { MeetingParticipant, MeetingTranscript, Meeting } from '../lib/meetings'
  import('../lib/meetings')
  // @ts-ignore
  export type { MemberStatus, MemberRole, WorkspaceRoleOption, Member } from '../lib/members'
  import('../lib/members')
  // @ts-ignore
  export type { Project, ProjectRoleValue, ProjectMember } from '../lib/projects'
  import('../lib/projects')
  // @ts-ignore
  export type { Sprint } from '../lib/sprints'
  import('../lib/sprints')
  // @ts-ignore
  export type { Task, TaskComment, TaskMember, BoardColumn } from '../lib/tasks'
  import('../lib/tasks')
  // @ts-ignore
  export type { TimezoneOption } from '../lib/timezones'
  import('../lib/timezones')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Head: UnwrapRef<typeof import('@inertiajs/vue3')['Head']>
    readonly Link: UnwrapRef<typeof import('@inertiajs/vue3')['Link']>
    readonly PROJECT_ROLES: UnwrapRef<typeof import('../lib/projects')['PROJECT_ROLES']>
    readonly archiveTypeLabel: UnwrapRef<typeof import('../lib/archive')['archiveTypeLabel']>
    readonly categoryBadgeVariant: UnwrapRef<typeof import('../lib/audit')['categoryBadgeVariant']>
    readonly cn: UnwrapRef<typeof import('../lib/utils')['cn']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly daysSince: UnwrapRef<typeof import('../lib/activity')['daysSince']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly detectTimezone: UnwrapRef<typeof import('../lib/timezones')['detectTimezone']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formatAuditTimestamp: UnwrapRef<typeof import('../lib/audit')['formatAuditTimestamp']>
    readonly formatDateEyebrow: UnwrapRef<typeof import('../lib/activity')['formatDateEyebrow']>
    readonly formatDueDate: UnwrapRef<typeof import('../lib/tasks')['formatDueDate']>
    readonly formatDuration: UnwrapRef<typeof import('../lib/meetings')['formatDuration']>
    readonly formatLastActive: UnwrapRef<typeof import('../lib/members')['formatLastActive']>
    readonly formatMeetingDate: UnwrapRef<typeof import('../lib/meetings')['formatMeetingDate']>
    readonly formatMeetingTime: UnwrapRef<typeof import('../lib/meetings')['formatMeetingTime']>
    readonly formatOccurredAt: UnwrapRef<typeof import('../lib/archive')['formatOccurredAt']>
    readonly formatSprintRange: UnwrapRef<typeof import('../lib/sprints')['formatSprintRange']>
    readonly getCodeHandler: UnwrapRef<typeof import('../lib/errors/errorCodeHandlers')['getCodeHandler']>
    readonly getCsrfToken: UnwrapRef<typeof import('../lib/csrf')['getCsrfToken']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getInitials: UnwrapRef<typeof import('../composables/useInitials')['getInitials']>
    readonly getSuggestions: UnwrapRef<typeof import('../lib/ai-suggestions')['getSuggestions']>
    readonly greeting: UnwrapRef<typeof import('../lib/activity')['greeting']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly handleError: UnwrapRef<typeof import('../lib/errors/handleError')['handleError']>
    readonly initializeTheme: UnwrapRef<typeof import('../composables/useAppearance')['initializeTheme']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isOverdue: UnwrapRef<typeof import('../lib/tasks')['isOverdue']>
    readonly isPastMeeting: UnwrapRef<typeof import('../lib/meetings')['isPastMeeting']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isSupportedTimezone: UnwrapRef<typeof import('../lib/timezones')['isSupportedTimezone']>
    readonly isValidMeetingLink: UnwrapRef<typeof import('../lib/meetings')['isValidMeetingLink']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly memberPresence: UnwrapRef<typeof import('../lib/members')['memberPresence']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseError: UnwrapRef<typeof import('../lib/errors/handleError')['parseError']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly router: UnwrapRef<typeof import('@inertiajs/vue3')['router']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly sprintStatusLabel: UnwrapRef<typeof import('../lib/sprints')['sprintStatusLabel']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly timezoneAbbreviation: UnwrapRef<typeof import('../lib/timezones')['timezoneAbbreviation']>
    readonly timezoneOffsetLabel: UnwrapRef<typeof import('../lib/timezones')['timezoneOffsetLabel']>
    readonly timezoneOptions: UnwrapRef<typeof import('../lib/timezones')['timezoneOptions']>
    readonly toDateTimeLocalValue: UnwrapRef<typeof import('../lib/meetings')['toDateTimeLocalValue']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toSpeakableText: UnwrapRef<typeof import('../composables/useVoiceOutput')['toSpeakableText']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateTheme: UnwrapRef<typeof import('../composables/useAppearance')['updateTheme']>
    readonly useAiAssistant: UnwrapRef<typeof import('../composables/useAiAssitant')['useAiAssistant']>
    readonly useAppearance: UnwrapRef<typeof import('../composables/useAppearance')['useAppearance']>
    readonly useAssistantPageContext: UnwrapRef<typeof import('../composables/useAiAssitant')['useAssistantPageContext']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCurrentWorkspace: UnwrapRef<typeof import('../composables/useCurrentWorkspace')['useCurrentWorkspace']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useDebounceFn: UnwrapRef<typeof import('@vueuse/core')['useDebounceFn']>
    readonly useDockContext: UnwrapRef<typeof import('../composables/useAiAssitant')['useDockContext']>
    readonly useFlashToasts: UnwrapRef<typeof import('../composables/useFlashToasts')['useFlashToasts']>
    readonly useForm: UnwrapRef<typeof import('@inertiajs/vue3')['useForm']>
    readonly useFormErrors: UnwrapRef<typeof import('../composables/useFormErrors')['useFormErrors']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useInitials: UnwrapRef<typeof import('../composables/useInitials')['useInitials']>
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotificationStore: UnwrapRef<typeof import('../stores/notification.store')['useNotificationStore']>
    readonly usePage: UnwrapRef<typeof import('@inertiajs/vue3')['usePage']>
    readonly useProjectTaskStream: UnwrapRef<typeof import('../composables/useProjectTaskStream')['useProjectTaskStream']>
    readonly useRemember: UnwrapRef<typeof import('@inertiajs/vue3')['useRemember']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly useUserTimezone: UnwrapRef<typeof import('../composables/useUserTimezone')['useUserTimezone']>
    readonly useVoiceInput: UnwrapRef<typeof import('../composables/useVoiceInput')['useVoiceInput']>
    readonly useVoiceOutput: UnwrapRef<typeof import('../composables/useVoiceOutput')['useVoiceOutput']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}