<?php

declare(strict_types=1);

namespace App\Support\Errors;

final class ErrorCode
{
    public const INTERNAL_ERROR = 'INTERNAL.ERROR';

    public const NOT_FOUND = 'NOT.FOUND';

    public const BAD_REQUEST = 'BAD.REQUEST';

    public const RATE_LIMITED = 'RATE.LIMITED';

    public const VALIDATION_FAILED = 'VALIDATION.FAILED';

    public const AUTH_UNAUTHENTICATED = 'AUTH.UNAUTHENTICATED';

    public const AUTH_FORBIDDEN = 'AUTH.FORBIDDEN';

    public const AUTH_SESSION_EXPIRED = 'AUTH.SESSION.EXPIRED';

    public const WORKSPACE_NOT_FOUND = 'WORKSPACE.NOT.FOUND';

    public const WORKSPACE_LIMIT_REACHED = 'WORKSPACE.LIMIT.REACHED';

    public const WORKSPACE_ALREADY_MEMBER = 'WORKSPACE.ALREADY.MEMBER';

    public const WORKSPACE_INVITATION_EXPIRED = 'WORKSPACE.INVITATION.EXPIRED';

    public const WORKSPACE_INVITATION_INVALID = 'WORKSPACE.INVITATION.INVALID';

    public const WORKSPACE_SLUG_ALREADY_EXISTS = 'WORKSPACE.SLUG.ALREADY.EXISTS';

    public const WORKSPACE_CREATION_FAILED = 'WORKSPACE.CREATION.FAILED';

    public const WORKSPACE_NO_ACTIVE = 'WORKSPACE.NO.ACTIVE';

    public const WORKSPACE_CANNOT_DELETE_ONLY = 'WORKSPACE.CANNOT.DELETE.ONLY';

    public const TEAM_CANNOT_REMOVE_OWNER = 'TEAM.CANNOT.REMOVE.OWNER';

    public const TEAM_CANNOT_REMOVE_SELF = 'TEAM.CANNOT.REMOVE.SELF';

    public const TEAM_CANNOT_CHANGE_OWNER_ROLE = 'TEAM.CANNOT.CHANGE.OWNER.ROLE';

    public const SPRINT_INVALID_TRANSITION = 'SPRINT.INVALID.TRANSITION';

    public const SPRINT_ALREADY_ACTIVE = 'SPRINT.ALREADY.ACTIVE';

    public const SPRINT_IS_COMPLETED = 'SPRINT.IS.COMPLETED';

    public const SPRINT_CARRY_OVER_TARGET_INVALID = 'SPRINT.CARRY.OVER.TARGET.INVALID';

    public const ASSISTANT_QUOTA_EXCEEDED = 'ASSISTANT.QUOTA.EXCEEDED';

    public const ASSISTANT_PROVIDER_UNAVAILABLE = 'ASSISTANT.PROVIDER.UNAVAILABLE';

    public const ASSISTANT_INVALID_TOOL_ARGUMENTS = 'ASSISTANT.INVALID.TOOL.ARGUMENTS';

    private function __construct() {}
}
